// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: immutable_options.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_immutable_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         59527,
		Name:          "example.immutable",
		Tag:           "varint,59527,opt,name=immutable",
		Filename:      "immutable_options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional bool immutable = 59527;
	E_Immutable = &file_immutable_options_proto_extTypes[0] // 唯一标识符应大于 50000，以避免与预定义选项冲突
)

var File_immutable_options_proto protoreflect.FileDescriptor

const file_immutable_options_proto_rawDesc = "" +
	"\n" +
	"\x17immutable_options.proto\x12\aexample\x1a google/protobuf/descriptor.proto:=\n" +
	"\timmutable\x12\x1d.google.protobuf.FieldOptions\x18\x87\xd1\x03 \x01(\bR\timmutableB\x15Z\x13goci-const-check/pbb\x06proto3"

var file_immutable_options_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil), // 0: google.protobuf.FieldOptions
}
var file_immutable_options_proto_depIdxs = []int32{
	0, // 0: example.immutable:extendee -> google.protobuf.FieldOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_immutable_options_proto_init() }
func file_immutable_options_proto_init() {
	if File_immutable_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_immutable_options_proto_rawDesc), len(file_immutable_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_immutable_options_proto_goTypes,
		DependencyIndexes: file_immutable_options_proto_depIdxs,
		ExtensionInfos:    file_immutable_options_proto_extTypes,
	}.Build()
	File_immutable_options_proto = out.File
	file_immutable_options_proto_goTypes = nil
	file_immutable_options_proto_depIdxs = nil
}
